# Generated by Django 2.1 on 2018-08-20 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0062_requestupdates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestUpdates',
            new_name='RequestUpdate',
        ),
    ]
