# Generated by Django 2.1 on 2018-08-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0063_auto_20180821_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestupdate',
            name='other_status',
            field=models.CharField(default='', max_length=255, verbose_name='Status description if none of the default statuses are applicable'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pro', 'In progess'), ('res', 'Resolved'), ('dup', 'Duplicate'), ('cls', 'Closed'), ('otr', 'Other'), ('sup', 'Supplied')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='requestupdate',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pro', 'In progess'), ('res', 'Resolved'), ('dup', 'Duplicate'), ('cls', 'Closed'), ('otr', 'Other'), ('sup', 'Supplied')], max_length=10),
        ),
    ]
