# Generated by Django 2.1 on 2018-08-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0062_contributorupdate'),
        ('mainapp', '0064_privaterescuecamp'),
    ]

    operations = [
    ]
