# Generated by Django 2.1 on 2018-08-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0065_merge_20180821_1422'),
        ('mainapp', '0065_merge_20180821_1426'),
    ]

    operations = [
    ]
