# Generated by Django 2.1 on 2018-08-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0066_merge_20180821_1500'),
        ('mainapp', '0068_auto_20180821_1710'),
    ]

    operations = [
    ]
