# Generated by Django 2.1 on 2018-08-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0069_merge_20180821_2300'),
        ('mainapp', '0072_auto_20180822_0000'),
    ]

    operations = [
    ]
