# Generated by Django 2.1 on 2018-08-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0073_merge_20180822_0018'),
        ('mainapp', '0073_merge_20180822_0015'),
    ]

    operations = [
    ]
